title: 'Projects'
email: 'deepikasandp@gmail.com'
description: 'A collection of my projects and work.'
theme: minima
url: 'https://deepikasandp.github.io'
baseurl: ''
custom_css: assets/css/custom.css
